default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: transporthacker
  password: transporthacker

development:
  <<: *default
  database: transporthacker_development

test: &test
  <<: *default
  database: transporthacker_test

production:
  <<: *default
  database: transporthacker_production

cucumber:
  <<: *test